{appl_spec,"sd",
 [
     {appl_name,"sd"},
     {vsn,"0.1.0"},
     {app,sd},
     {gitpath,"https://github.com/joq62/sd.git"},
     {local_resource_type,[sd,common]},
     {target_resource_type,[nodelog]}  
 ]}.
